{% set version = "0.3.11" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://github.com/benfred/py-spy/archive/v{{ version }}.tar.gz
  sha256: 094cfb80e2c099763453fc39cfa9c46cfa423afa858268c6a7bc0d867763b014

build:
  number: 1
  # this is producing multiple outputs, one of which is failing.
  skip: true  # [win and (rust_compiler == 'rust-gnu')]
  # Windows 32-bit is not supported upstream via readme:
  # https://github.com/benfred/py-spy#does-py-spy-support-32-bit-windows-integrate-with-pypy-work-with-usc2-versions-of-python2
  skip: true  # [win32]
  # Builds on Linux need a newer glibc: https://github.com/conda-forge/conda-forge.github.io/issues/900
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - libunwind  # [linux and x86_64]
  run:
    - libunwind  # [linux and x86_64]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
