{% set version = "0.3.1" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://github.com/benfred/py-spy/archive/v{{ version }}.tar.gz
  sha256: 073a31680de52df9ab2a4b49d6899c727e4354242a005d1dae2cba5ad984d4dc

build:
  number: 0
  # Builds on Windows timeout
  # Builds on Linux need a newer glibc: https://github.com/conda-forge/conda-forge.github.io/issues/900
  skip: true  # [not osx]
  missing_dso_whitelist:          # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - rust
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
  host:
    - libunwind  # [linux]
  run:
    - libunwind  # [linux]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
