{% set version = "0.3.10" %}

package:
  name: py-spy
  version: {{ version }}

source:
  url: https://github.com/benfred/py-spy/archive/v{{ version }}.tar.gz
  sha256: 6c07096d227c08dee8a6526ff0a4ceadbe11eb27a131ab147e9d82dde52f3177

build:
  number: 1
  # Builds on Linux need a newer glibc: https://github.com/conda-forge/conda-forge.github.io/issues/900
  missing_dso_whitelist:   # [osx]
    - /usr/lib/libresolv.9.dylib  # [osx]

requirements:
  build:
    - sysroot_linux-64 2.17  # [linux64]
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
  host:
    - libunwind  # [linux]
  run:
    - libunwind  # [linux]

test:
  commands:
    - py-spy --help

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  summary: Sampling profiler for Python programs
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
