{% set name = "py-spy" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/benfred/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 6abc303d4e2db30d472997838f83d547a990df7747e1d327249a757863ee9225
build:
  number: 0

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - libunwind {{ libunwind }}  # [linux64]
  run:
    # Version through run_exports
    - libunwind  # [linux64]

test:
  source_files:  # [not osx]
    - tests  # [not osx]
  requires:
    - pip
    - pytest  # [not osx]
    # For some reason we need to pin specific version to run the tests.
    # Error: Failed to find python version from target process
    - python 3.12  # [not osx]
  commands:
    - pip check
    - py-spy --help
    # Those tests require root on OSX.
    - python -m unittest tests/integration_test.py  # [not osx]

about:
  home: https://github.com/benfred/py-spy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Sampling profiler for Python programs
  description: |
    py-spy is a sampling profiler for Python programs. 
    It lets you visualize what your Python program is spending time on 
    without restarting the program or modifying the code in any way. 
    py-spy is extremely low overhead: it is written in Rust for speed 
    and doesn't run in the same process as the profiled Python program. 
    This means py-spy is safe to use against production Python code.
  dev_url: https://github.com/benfred/py-spy
  doc_url: https://github.com/benfred/py-spy

extra:
  recipe-maintainers:
    - xhochy
